name: build
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-|
      - name: Generate Maven settings
        uses: whelk-io/maven-settings-xml-action@v18
        with:
          servers: >
            [
              {
                "id": "itbRepoRead",
                "username": "${{ secrets.ITB_MVN_REPO_USER }}",
                "password": "${{ secrets.ITB_MVN_REPO_PASS }}"
              }
            ]
          profiles: >
            [
              {
                "id": "itbRepoRead",
                "properties": {
                  "itbRepoReadUrl": "${{ secrets.ITB_MVN_REPO_URL }}"
                }
              }
            ]
          active_profiles: >
            [
              "itbRepoRead"
            ]
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Generate coverage badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.3.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: >
            shaclvalidator-common/target/site/jacoco/jacoco.csv
            shaclvalidator-jar/target/site/jacoco/jacoco.csv
            shaclvalidator-service/target/site/jacoco/jacoco.csv
            shaclvalidator-web/target/site/jacoco/jacoco.csv
            shaclvalidator-war/target/site/jacoco/jacoco.csv
      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
      - name: Commit coverage badge (if changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'ISA2ITB'
            git config --global user.email 'ISA2ITB@users.noreply.github.com'
            git add .github/badges/branches.svg
            git add .github/badges/jacoco.svg
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push --force origin master
          fi